backend:
  name: github
  repo: haohanqi/wishAball
media_folder: static/assets
public_folder: /assets

collections: 
  - name: blog
    label: Blog
    folder: src/markdown
    create: true
    fields:
      - {name: path, label: Path, widget: string}
      - {name: date, label: Date, widget: datetime}
      - {name: title, label: Title, widget: string}
      - {name: author, label: Author, widget: string, required: false}
      - {name: body, label: Body, widget: markdown}

  - name: data
    label: Data
    files:
    - file: src/data/wishASportData.json
      name: wishASportData
      label: Wish-A-Sport-Data
      fields: 
          - label: wish-a-sport
            name: wishasport
            widget: list
            allow_add: true
            fields:
              - {name: path, label: Path, widget: string}
              - {name: sport, label: Sport, widget: string}
              - {name: organization, label: Organization, widget: string}
              - {name: website, label: Website, widget: string}
              - {name: phone, label: Phone, widget: string}
              - {name: address, label: Address, widget: string}
              - name: coAddress
                label: Coaddress
                widget: object
                fields:
                    - {name: lat, label: Lat, widget: number, value_type: float}
                    - {name: lng, label: Lng, widget: number, value_type: float}
              - {name: city, label: City, widget: string} 
              - {name: img, label: Img, widget: image}
              - {name: info, label: Info, widget: text} 

  - name: pageContent
    label: Page-Content
    files:
    - file: src/pageContent/MainPage.json
      name: mainPage
      label: Main-Page
      fields: 
        - name: entrySection
          label: Entry-Section
          widget: object
          fields: 
            - name: wishASport
              label: WishASport
              widget: object
              fields: 
               - name: english
                 label: English
                 widget: object
                 fields:
                    - {name: title, label: Title, widget: string }
                    - {name: description, label: Description, widget: text }
               - name: chinese
                 label: Chinese
                 widget: object
                 fields:
                    - {name: title, label: Title, widget: string }
                    - {name: description, label: Description, widget: text }
            - name: wishAClass
              label: WishAClass
              widget: object
              fields: 
                 - name: english
                   label: English
                   widget: object
                   fields:
                    - {name: title, label: Title, widget: string }
                    - {name: description, label: Description, widget: text }
                 - name: chinese
                   label: Chinese
                   widget: object
                   fields:
                    - {name: title, label: Title, widget: string }
                    - {name: description, label: Description, widget: text }
    - file: src/pageContent/AboutPage.json
      name: aboutPage
      label: About-Page
      fields: 
        - name: entrySection
          label: Entry-Section
          widget: object
          fields: 
           - name: english
             label: english
             widget: object
             fields:
              - {name: title, label: Title, widget: string }
              - {name: description, label: Description, widget: markdown }
           - name: chinese
             label: Chinese
             widget: object
             fields:
              - {name: title, label: Title, widget: string }
              - {name: description, label: Description, widget: markdown }
        - name: aboutSection
          label: About-Section
          widget: object
          fields: 
           - name: english
             label: english
             widget: object
             fields:
              - {name: title, label: Title, widget: string }
              - {name: description, label: Description, widget: markdown }
           - name: chinese
             label: Chinese
             widget: object
             fields:
              - {name: title, label: Title, widget: string }
              - {name: description, label: Description, widget: markdown }
        - name: verticalPanel
          label: verticalPanel
          widget: list
          require: false
          allow_add: true
          fields: 
            - name: panel
              label: Panel
              widget: object
              fields:
                 - name: english
                   label: English
                   widget: object
                   fields:
                     - {name: title, label: Title, widget: string }
                     - {name: description, label: Description, widget: markdown }
                 - name: chinese
                   label: Chinese
                   widget: object
                   fields:
                     - {name: title, label: Title, widget: string }
                     - {name: description, label: Description, widget: markdown }
        - name: whatDoWeDoSection
          label: WhatDoWeDoSection
          widget: list
          allow_add: true
          fields: 
            - name: whatDoWeDo
              label: WhatDoWeDo
              widget: object
              fields:
                - name: english
                  label: English
                  widget: object
                  fields: 
                    - {name: title, label: Title, widget: string}
                    - {name: description, label: Description, widget: string}
                - name: chinese
                  label: Chinese
                  widget: object
                  fields: 
                    - {name: title, label: Title, widget: string}
                    - {name: description, label: Description, widget: string}
        - name: workWithUs
          lable: WorkWithUs
          widget: list
          allow_add: true
          fields: 
            - name: work
              label: Work
              widget: object
              fields: 
                - name: chinese
                  label: Chinese
                  widget: object
                  fields:
                    - {name: workDescription, label: WorkDescription, widget: text}
                - name: english
                  label: English
                  widget: object
                  fields:
                    - {name: workDescription, label: WorkDescription, widget: text}
    - file: src/pageContent/ContactInfo.json 
      name: contactInfo
      label: ContactInfo
      fields: 
        - {name: email, label: Email, widget: string, required: false}
        - {name: phone, label: Phone, widget: string, required: false}
        - {name: location, label: Location, widget: string, required: false}
        - name: socalMediaLink
          label: SocalMediaLink
          required: false
          widget: object
          fields:
            - {name: insLink, label: InsLink, widget: string, required: false}
            - {name: weChetLink, label: WechetLink, widget: string, required: false}
    - file: src/pageContent/Footer.json
      name: footer
      label: Footer   
      fields: 
        - name: intro
          label: Introduction
          widget: object
          fields: 
            - name: chinese
              label: Chinese
              widget: object
              required: false
              fields: 
                - {name: title, label: Title, widget: string}
                - {name: description, label: Description, widget: text}
            - name: english
              label: English
              widget: object
              fields: 
                - {name: title, label: Title, widget: string}
                - {name: description, label: Description, widget: text}
        - name: links
          label: Links
          widget: list
          allow_add: true
          fields: 
            - name: linkItem
              label: LinkItem
              widget: object
              fields:
                - {name: linkName, label: LinkName, widget: string}
                - {name: linkAddress, label: LinkAddress, widget: string}

            



